services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.22-bookworm
    container_name: go-app
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "cd /workspace && go run main.go"
    ports:
      - 9000:9000

  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moviesdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: