definitions:
  internal_api.APIMovie:
    properties:
      director:
        type: string
      id:
        type: string
      title:
        type: string
      year:
        type: integer
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Responds with OK if the service is up and running
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - health
  /movies:
    get:
      description: Get all movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_api.APIMovie'
            type: array
      summary: Retrieve list of movies
      tags:
      - movies
  /movies/{id}:
    get:
      consumes:
      - application/json
      description: Get a single movie by its ID
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_api.APIMovie'
        "404":
          description: Movie not found
      summary: Get a movie
      tags:
      - movies
swagger: "2.0"
