name: Build and Deploy to Docker Hub

on:
  workflow_run:
    workflows: ["Application Tests"]
    types:
    - completed
    branches: [main]

jobs:
  check_previous_success:
    runs-on: ubuntu-latest
    outputs:
      success: ${{ steps.check_success.outputs.success }}
    steps:
    - name: Check if previous workflows were successful
      id: check_success
      run: |
        if [[ "${{ github.event.workflow_run.conclusion }}" != "success" ]]; then
          echo "One or more of the required workflows failed."
          echo "::set-output name=success::false"
          exit 1
        fi
        echo "::set-output name=success::true"
  build-and-push:
    needs: check_previous_success
    if: needs.check_previous_success.outputs.success == 'true'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          aaronzi/go-demo-api:${{ github.sha }}
          aaronzi/go-demo-api:latest
        platforms: linux/amd64,linux/arm64

    # Mirror the image to GitHub Packages
    - name: Pull Docker Image from Docker Hub
      run: docker pull aaronzi/go-demo-api:latest

    - name: Tag the Image for GitHub Packages
      run: docker tag aaronzi/go-demo-api:latest ghcr.io/${{ github.repository_owner }}/go-demo-api:latest

    - name: Log in to GitHub Packages
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Image to GitHub Packages
      run: docker push ghcr.io/${{ github.repository_owner }}/go-demo-api:latest